const monitores = [
  {
    monitor_id: 1,
    firstName: 'Gustavo',
    lastName: 'Felippe',
    discordID: '533170999990943744',
    discordHandle: 'Gustavo Felippe',
    email: 'gustavo@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/gustavo-pd',
    image: '/path/to/image.png',
  },
  {
    monitor_id: 2,
    firstName: 'Fernanda',
    lastName: 'Sabrina',
    discordID: '1204433797777465418',
    discordHandle: 'Fernanda Oliveira',
    email: 'fernandasabrina@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/fernandas',
    image: '/path/to/image2.png',
  },
  {
    monitor_id: 3,
    firstName: 'Larissa',
    lastName: 'Felipe',
    discordID: '1180131301446127637',
    discordHandle: 'Larissa',
    email: 'larissa@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/larissafelipe/monitoria-1',
    image: '/path/to/image3.png',
  },
  {
    monitor_id: 4,
    firstName: 'Gabriel',
    lastName: 'Moura',
    discordID: '345678901234567890',
    discordHandle: 'gabrielm',
    email: 'gabriel@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/gabrielm',
    image: '/path/to/image4.png',
  },
  {
    monitor_id: 5,
    firstName: 'Emannuel',
    lastName: 'Costa',
    discordID: '456789012345678901',
    discordHandle: 'emannuelc',
    email: 'emannuel@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/emannuelc',
    image: '/path/to/image5.png',
  },
  {
    monitor_id: 6,
    firstName: 'João',
    lastName: 'Vitor',
    discordID: '567890123456789012',
    discordHandle: 'joaov',
    email: 'joao@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/joaov',
    image: '/path/to/image6.png',
  },
  {
    monitor_id: 7,
    firstName: 'Eduardo',
    lastName: 'Coelho',
    discordID: '678901234567890123',
    discordHandle: 'eduardoc',
    email: 'eduardo@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/eduardoc',
    image: '/path/to/image7.png',
  },
  {
    monitor_id: 8,
    firstName: 'Lucca',
    lastName: 'Fernandes',
    discordID: '789012345678901234',
    discordHandle: 'luccaf',
    email: 'lucca@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/luccaf',
    image: '/path/to/image8.png',
  },
];

export default monitores;
