import joaoImage from '../../img/monitores/joao.svg';

const monitores = [
  {
    monitor_id: 1,
    firstName: 'Gustavo',
    lastName: 'Felippe',
    discordID: '533170999990943744',
    discordHandle: 'Gustavo Felippe',
    email: 'gustavo@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/gustavo-pd',
    image: '../../img/monitores/gu.svg',
  },
  {
    monitor_id: 2,
    firstName: 'Fernanda',
    lastName: 'Sabrina',
    discordID: '1204433797777465418',
    discordHandle: 'Fernanda Oliveira',
    email: 'fernandasabrina@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/fernandas',
    image: '../../img/monitores/fernanda.svg',
  },
  {
    monitor_id: 3,
    firstName: 'Larissa',
    lastName: 'Felipe',
    discordID: '1180131301446127637',
    discordHandle: 'Larissa',
    email: 'larissafelipe@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/larissafelipe/monitoria-1',
    image: '../../img/monitores/lari.svg',
  },
  {
    monitor_id: 4,
    firstName: 'Gabriel',
    lastName: 'Mauro',
    discordID: '345678901234567890',
    discordHandle: 'gabrielm',
    email: 'gabriel.mauro@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/gabrielm',
    image: '../../img/monitores/gabrielMauro.svg',
  },
  {
    monitor_id: 5,
    firstName: 'Emannuel',
    lastName: 'Costa',
    discordID: '456789012345678901',
    discordHandle: 'emannuelc',
    email: 'emannuelcosta@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/emannuelcosta/monitoria-obrigatoria',
    image: '../../img/monitores/mannel.svg',
  },
  {
    monitor_id: 6,
    firstName: 'João',
    lastName: 'Vitor',
    discordID: '567890123456789012',
    discordHandle: 'joaov',
    email: 'joaocardoso@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/joaocardosopd/monitoria',
    image: joaoImage,
  },
  {
    monitor_id: 7,
    firstName: 'Eduardo',
    lastName: 'Coelho',
    discordID: '678901234567890123',
    discordHandle: 'eduardoc',
    email: 'eduardocoelho@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/eduardoc',
    image: '../../img/monitores/eduardo.svg',
  },
  {
    monitor_id: 8,
    firstName: 'Lucca',
    lastName: 'Fernandes',
    discordID: '789012345678901234',
    discordHandle: 'luccaf',
    email: 'lucca@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/luccaf',
    image: '../../img/monitores/lucca.svg',
  },
  {
    monitor_id: 9,
    firstName: 'Felipe',
    lastName: 'Campos',
    discordID: '1217554725432594540',
    discordHandle: 'Felipe Campos',
    email: 'felipe@projetodesenvolve.com.br',
    calendlyLink: 'https://calendly.com/felipec',
    image: '../../img/monitores/felipe.svg',
  },
];

export default monitores;
